### ISSUE TITLE
'Connection' object has no attribute '_socket' in Co-Simulation between SUMO and CARLA

### ISSUE THREAD

**Issue by ShenZC25** [Dekai21/Multi_Agent_Intersection#5]
Thank you very much for your excellent work. I encountered the following problems when using SUMO and CARLA for joint simulation (it seems that there were similar problems in previous issues, but I still don't know how to solve them)

Traceback (most recent call last):
File "run_synchronization.py", line 396, in
synchronization_loop(arguments)
File "run_synchronization.py", line 325, in synchronization_loop
synchronization.tick()
File "run_synchronization.py", line 117, in tick
self.sumo.tick()
File "F:\CARLA_0.9.10\WindowsNoEditor\Co-Simulation\Sumo\sumo_integration\sumo_simulation.py", line 532, in tick
traci.simulationStep()
File "F:\Program Files\Eclipse\Sumo\tools\traci\main.py", line 207, in simulationStep
return _connections[""].simulationStep(step)
File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 323, in simulationStep
result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 185, in _sendCmd
return self._sendExact()
File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 83, in _sendExact
if self._socket is None:
AttributeError: 'Connection' object has no attribute '_socket'

This seems to be that I have too many cars colliding at the intersection, and then some cars can't be removed. If it is caused by this reason, please tell me how to solve it (for example, how to remove the vehicle), otherwise please help me to confirm the problem.

Besides, there are some other problems. That is to say, when I was conducting joint simulation, I found that the simulation time of SUMO and CARLA was out of sync. Can you tell me why? thank you
![Snipaste_2023-11-30_22-25-15](https://github.com/Dekai21/Multi_Agent_Intersection/assets/89288084/d1611b87-ef5c-4353-bc49-de56c3e4e72e)

As the picture shows, SUMO has crashed, but CARLA hasn't, but my understanding is that they should be synchronized?

Looking forward to your answer, thank you.

**Comment by ShenZC25** [comment]
> Thank you very much for your excellent work. I encountered the following problems when using SUMO and CARLA for joint simulation (it seems that there were similar problems in previous issues, but I still don't know how to solve them)
> 
> Traceback (most recent call last): File "run_synchronization.py", line 396, in synchronization_loop(arguments) File "run_synchronization.py", line 325, in synchronization_loop synchronization.tick() File "run_synchronization.py", line 117, in tick self.sumo.tick() File "F:\CARLA_0.9.10\WindowsNoEditor\Co-Simulation\Sumo\sumo_integration\sumo_simulation.py", line 532, in tick traci.simulationStep() File "F:\Program Files\Eclipse\Sumo\tools\traci\main.py", line 207, in simulationStep return _connections[""].simulationStep(step) File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 323, in simulationStep result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step) File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 185, in _sendCmd return self._sendExact() File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 83, in _sendExact if self._socket is None: AttributeError: 'Connection' object has no attribute '_socket'
> 
> This seems to be that I have too many cars colliding at the intersection, and then some cars can't be removed. If it is caused by this reason, please tell me how to solve it (for example, how to remove the vehicle), otherwise please help me to confirm the problem.
> 
> Besides, there are some other problems. That is to say, when I was conducting joint simulation, I found that the simulation time of SUMO and CARLA was out of sync. Can you tell me why? thank you ![Snipaste_2023-11-30_22-25-15](https://private-user-images.githubusercontent.com/89288084/286965317-d1611b87-ef5c-4353-bc49-de56c3e4e72e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDA3NzgsIm5iZiI6MTcwMTQwMDQ3OCwicGF0aCI6Ii84OTI4ODA4NC8yODY5NjUzMTctZDE2MTFiODctZWY1Yy00MzUzLWJjNDktZGU1NmMzZTRlNzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAzMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NmY4YzEzZWJjYmNhZDQxZWQxYWQ1YzRlODk1ZmI1OTNjYTIxY2M0MmEwMDZkNWRlZTlhODdmOGEzODc4MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X8DBtiNqRksI4ZS8YWt2xJIR9d2-_-DgL91Hrnj7c7Y)
> 
> As the picture shows, SUMO has crashed, but CARLA hasn't, but my understanding is that they should be synchronized?
> 
> Looking forward to your answer, thank you.

In addition, I also encountered the following problems when conducting joint simulation:
WARNING: cannot parse georeference: ''. Using default values.

It seems to be carla's problem, and it has already been solved (it can be found in carla's github issuses). But I don't know why I still encounter this problem.
The complete error information is as follows:



(mvn) F:\CARLA_0.9.10\WindowsNoEditor\Co-Simulation\Sumo>python run_synchronization.py  sumo_files/sumocfg/09-11-15-30-00400-0.09-val_10m_35m-7.sumocfg  --tls-manager carla  --sumo-gui  --step-length 0.1  --pretrained-weights F:\PycharmProjects\MVI\trained_params\sumo_1130\model_gnn_np_sumo_1130_e3_10760.pth
INFO: Starting new sumo server...
INFO: Remember to press the play button to start the simulation
WARNING: cannot parse georeference: ''. Using default values. 
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla0' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla1' is not known.
Error! Vehicle 'carla2' is not known.
Error! Vehicle 'carla2' is not known.
Error! Vehicle 'carla2' is not known.
Error! Vehicle 'carla2' is not known.

**Comment by Dekai21** [comment]
The issue seems to be caused by a crash in the connection between SUMO and CARLA. I didn’t encounter this problem on my laptop, so I’m not entirely sure if it’s related to vehicle collisions in SUMO.

However, I’ve modified the SUMO-side code to force vehicles to stay on their routes in [this commit](https://github.com/Dekai21/Multi_Agent_Intersection/commit/2b524a93183ca7c2c0d246a4bbc1f9672511860b). Hopefully, this helps resolve the issue.
